[package]
name = "jbl"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "4.5.4"
cosmic-text = "0.11.2"
image = "0.25.1"
regex = "1.10.4"
